In [1]:
import numpy as np 
import pandas as pd 
from pandas import Series,DataFrame

from numpy import random
from numpy.random import randn

In [ ]:
dframe = pd.read_csv('lec25.csv' , sep = ',', header = None)

dframe

In [ ]:
pd.read_csv('lec25.csv' , header=None , nrows = 2)

In [10]:
dframe.to_csv('mytextdata_out.csv')

In [ ]:
import sys

dframe.to_csv(sys.stdout , columns = [0,1,2])

In [22]:
json_obj = """
{ "zoo_animal" : "Lion",
  "food" : ["Meat" , "Veggies" ,"Honey" ],
  "fur" : "Golden",
  "clothes" : null,
  "diet" : [{"zoo_animal": "Gazelle" ,"food" : "Grass" , "fur":"Brown"}]
  }
"""

In [23]:
import json

data = json.loads(json_obj)

data

{'clothes': None,
 'diet': [{'food': 'Grass', 'fur': 'Brown', 'zoo_animal': 'Gazelle'}],
 'food': ['Meat', 'Veggies', 'Honey'],
 'fur': 'Golden',
 'zoo_animal': 'Lion'}

In [24]:
json.dumps(data)

'{"zoo_animal": "Lion", "food": ["Meat", "Veggies", "Honey"], "fur": "Golden", "clothes": null, "diet": [{"zoo_animal": "Gazelle", "food": "Grass", "fur": "Brown"}]}'

In [26]:
dframe = DataFrame(data['diet'])

dframe

food    fur zoo_animal
0  Grass  Brown    Gazelle

In [27]:
from pandas import read_html

In [28]:
url = 'https://www.fdic.gov/bank/individual/failed/banklist.html'

In [31]:
dframe_list = pd.io.html.read_html(url)

dframe = dframe_list[0]

dframe.columns.values

array(['Bank Name', 'City', 'ST', 'CERT', 'Acquiring Institution',
       'Closing Date', 'Updated Date'], dtype=object)

In [ ]:
xlsFile = pd.ExcelFile('Hours.xlsx')

dframe = xlsFile.parse('Sheet1')

dframe

In [ ]:
dframe1 = DataFrame({'Key' : ['X' , 'Z' ,'Y' , 'Z' , 'X' , 'X'] , 'data_set_1' :np.arange(6)})
    
dframe1

In [41]:
dframe2 = DataFrame({'Key' : ['Q' , 'Y' , 'Z'] , 'data_set_2':[1,2,3]})

dframe2

Key  data_set_2
0   Q           1
1   Y           2
2   Z           3

In [ ]:
pd.merge(dframe1 ,dframe2, on = 'Key' , how ='outer')

In [ ]:
dframe3 = DataFrame({'Key' : ['X' ,'X', 'X' ,'Y','Z','Z'] , 'data_set_3':range(6)})

dframe3

In [ ]:
dframe4 = DataFrame({'Key' : ['Y' ,'Y' ,'X' ,'X' ,'Z'] , 'data_set_4' : range(5)})

dframe4

In [ ]:
pd.merge(dframe3, dframe4)

In [ ]:
df_left = DataFrame({'key1': ['SF' , 'SF' , 'LA'],
                    'key2' : ['one' , 'two' , 'one'],
                    'left_data' :[10,20,30]})

df_left

In [ ]:
df_right = DataFrame({'key1': ['SF' ,'SF', 'LA','LA'] , 
                     'key2':['one' , 'one','two','two'],
                     'right_data' :[40,50,60,70]})
                     
df_right

In [ ]:
pd.merge(df_left , df_right, on = ['key1' , 'key2'] , how = 'outer')

In [62]:
df_right_hr = DataFrame(np.arange(10).reshape(5,2),
                       index = [['LA' ,'LA' ,'SF' ,'SF' ,'SF'],
                               [20,10,10,10,20]],
                       columns = ['col_1' , 'col_2'])

df_right_hr

col_1  col_2
LA 20      0      1
   10      2      3
SF 10      4      5
   10      6      7
   20      8      9

In [65]:
arr1 = np.arange(9).reshape(3,3)

arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
np.concatenate([arr1 , arr1],axis =0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
ser1 = Series([0,1,2] , index = ['T', 'U' , 'V'])

ser2 = Series([3,4] , index = ['X' , 'Y'])

ser1



In [ ]:
pd.concat([ser1,ser2] ,keys = ['cat1' , 'cat2'])

In [ ]:
dframe1 = DataFrame(np.random.randn(4,3) , columns = ['X' ,'Y' ,'Z'])

dframe2 = DataFrame(np.random.randn(3,3) , columns = ['Y' , 'Q' , 'X'])

dframe1

In [ ]:
pd.concat([dframe1 , dframe2] , ignore_index = True)

In [ ]:
ser1 = Series([2,np.nan,4,np.nan,6,np.nan] , index = ['Q','R','S','T','U','V'])

ser1

In [ ]:
ser2 = Series(np.arange(len(ser1)),dtype = np.float64, index = [['Q','R','S','T','U','V']])

ser2

In [ ]:
Series(np.where(pd.isnull(ser1), ser2,ser1) , index = ser1.index)

In [ ]:
ser1.combine_first(ser2)

In [ ]:
nan = np.nan

dframe_odds = DataFrame({'X' : [1.,nan,3.,nan],
                        'Y': [nan , 5., nan,7.],
                        'Z' : [nan , 9. , nan, 11]})

dframe_odds

In [ ]:
dframe_even = DataFrame({'X': [2.,4.,nan,6.,8.],
                        'Y': [nan,10.,12.,14.,16.]})

dframe_even

In [ ]:
dframe_odds.combine_first(dframe_even)

In [16]:
dframe1 = DataFrame(np.arange(8).reshape(2,4),
                   index = pd.Index(['LA' , 'SF'],name = 'city'),
                   columns = pd.Index(['A' , 'B' , 'C','D'],name= 'letter'))

dframe1

letter  A  B  C  D
city              
LA      0  1  2  3
SF      4  5  6  7

In [ ]:
dframe_st = dframe1.unstack('city')

dframe_st

In [34]:
dframe = pd.concat([ser1 , ser2] , keys = ['Alpha' , 'Beta'])

dframe

Alpha  Q    0
       X    1
       Y    2
Beta   X    4
       Y    5
       Z    6
dtype: int64

In [23]:
ser1 = Series([0,1,2],index = ['Q','X','Y'])

ser2 = Series([4,5,6] , index = ['X' , 'Y' , 'Z'])

In [ ]:
dframe.stack()

In [ ]:
import pandas.util.testing as tm; tm.N = 3

def unpivot(frame):
    N, K = frame.shape
    
    data = {'value' : frame.values.ravel('F'),
           'variable' : np.asarray(frame.columns).repeat(N),
           'date' : np.tile(np.asarray(frame.index) , K)}
    
    return DataFrame(data , columns=['date' , 'variable' , 'value'])

dframe = unpivot(tm.makeTimeDataFrame())

dframe

In [ ]:
dframe_piv = dframe.pivot('date' , 'variable' ,'value')

dframe_piv


In [49]:
dframe = DataFrame({'key1': ['A']*2 + ['B']*3 ,'key2' : [2,2,2,3,3]})

dframe

key1  key2
0    A     2
1    A     2
2    B     2
3    B     3
4    B     3

In [ ]:
dframe.drop_duplicates(['key1'])

In [ ]:
dframe = DataFrame({'city' : ['Alma' , 'Brian Head' , 'Fox Park'],
                   'altitude' : [3158,3000,2762]})

dframe

In [ ]:
state_map = {'Alma' : 'Colorado' , 'Brian Head' : 'Utah' , 'Fox Park' : 'Wyoming'}

dframe['state'] = dframe['city'].map(state_map)

dframe

In [ ]:
ser1 = Series([1,2,3,4,1,2,3,4])

ser1.replace({4 : np.nan})

In [ ]:
dframe = DataFrame(np.arange(12).reshape(3,4),
                  index = ['NY' , 'LA' , 'SF'],
                  columns = ['A' ,'B' , 'C' , 'D'])

dframe.index.map(str.lower)

dframe.rename(index ={'ny' : 'New York'},
             columns = {'A' : 'Alpha'})

In [ ]:
years = [1990 , 1991 , 1992,2008 ,2012 ,2015 ,1984 ,1987 ,2013 ,2008 ,1999]

decade_bins = [1960,1970,1980,1990,2000,2010,2020]

decade_cat = pd.cut(years, decade_bins)

decade_cat.categories

In [ ]:
pd.value_counts(decade_cat)

In [ ]:
pd.cut(years, 2, precision =1)

In [ ]:
np.random.seed(12345)

dframe  = DataFrame(np.random.randn(1000,4))

dframe.tail()

In [ ]:
dframe.describe()

In [ ]:
col = dframe[0]

col.head()

In [ ]:
col[(np.abs(dframe)>3).any(1)]

In [ ]:
dframe[np.abs(dframe)>3] = np.sign(dframe)*3

dframe.describe()

In [ ]:
dframe = DataFrame(np.arange(16).reshape(4,4))

blender = np.random.permutation(4)

blender

dframe

In [ ]:
dframe.take(blender)

In [81]:
box = np.array([1,2,3])


shaker = np.random.randint(0,len(box),size=10)

shaker

array([0, 0, 2, 1, 1, 2, 1, 1, 0, 1])

In [82]:
hand_grabs = box.take(shaker)

hand_grabs

array([1, 1, 3, 2, 2, 3, 2, 2, 1, 2])